language: generic

git:
  depth: 3

sudo: required

services:
  - docker

branches:
    only:
        # CI Development Branches
        - /ci//.*/
        - master1
        - 5.41
        # Regex to build tagged commits with version numbers
        - /\d+\.\d+(\.\d+)?(\S*)?$/

os:
    - linux

addons:
  apt:
    packages:
      - docker-ce
    
install:
    - df -h
    - docker build --tag gmt .
    - df -h
    
script:
    - docker run --rm gmt defaults -Vd
    - docker run --rm gmt pscoast -R0/10/0/10 -JM6i -Ba -Ggray -P -Vd > test.ps


notifications:
    email: false
