language: c

sudo: required

services:
  - docker

branches:
    only:
        # CI Development Branches
        - ci/*
        - master
        - 5.41
        # Regex to build tagged commits with version numbers
        - /\d+\.\d+(\.\d+)?(\S*)?$/

os:
    - linux
    #- osx

addons:
  apt:
    packages:
      - docker-ce
    
install:
    - docker build --tag gmt .
    
script:
    - docker run --rm gmt defaults -Vd
    - docker run --rm gmt pscoast -R0/10/0/10 -JM6i -Ba -Ggray -P -Vd > test.ps


notifications:
    email: false
